name: 'Saplings - Component base'
description: 'Shared configuration for Saplings component types.'
type: 'Site'
install:
  # Core.
  - options
  - text
  # Contrib.
  - paragraphs
  - saplings_paragraphs
  - ui_icons
  - ui_icons_backport
  - ui_icons_field
  - ui_icons_picker
