name: 'Saplings - Component base'
description: 'Base configuration for Saplings component types.'
type: 'Site'
install:
  # Core.
  # - example
  # Contrib.
  # - example
config:
  import:
    # Core.
    # module_name:
    #  - one.config.name
    # Contrib.
    # module_name: "*"
