name: 'Saplings - Component base'
description: 'Base configuration for Saplings component types.'
type: 'Site'
install:
  # Core.
  # - example
  # Contrib.
  - bootstrap_layout_classes
  - paragraphs
  - field_ui
config:
  import:
    # Core.
    # module_name:
    # field_ui: '*'
    # Contrib.
    paragraphs: "*"
