name: 'Saplings - Component base'
description: 'Shared configuration for Saplings component types.'
type: 'Site'
install:
  # Core.
  - text
  # Contrib.
  - focal_point
  - nomarkup
  - paragraphs
  - responsive_image
  - saplings_custom
