name: 'Saplings - Component base'
description: 'Base configuration for Saplings component types.'
type: 'Site'
recipes:
  - saplings-content-base
install:
  # Core.
  - text
  # Contrib.
  - paragraphs
