name: 'Saplings - Component base'
description: 'Base configuration for Saplings component types.'
type: 'Site'
recipes:
  - saplings-content-base
install:
  # Core.
  # - example
  # Contrib.
  - bootstrap_layout_classes
  - paragraphs
config:
  import:
    # Core.
    # module_name:
    # example: '*'
    # Contrib.
